### PR TITLE
Correctly populate SimpleADCWindow TA fields

### LINKED ISSUE #84: TAM ADC Simple Window: Incorrect ADC Peak
https://github.com/DUNE-DAQ/triggeralgs/blob/b146de11c70917dad70666fe40bbe5b8346e8c86/src/TAMakerADCSimpleWindowAlgorithm.cpp#L99

The assignment of the ADC peak for this algorithm is not true to the TP contents. There is no calculation done for what the ADC peak actually is since it strictly uses the last TP in the window. This may be true of other algorithms which make use of `TPWindow`, but I have not yet checked.

It may be worth it to keep track of the `argmax` of ADC peak for the TP list in `TPWindow` for easier updating for the moving window and assignment during TA construction.

### PR DESCRIPTION
**Pull request by alessandrothea**
# Description

See issue https://github.com/DUNE-DAQ/triggeralgs/issues/84

Additionally, this PR moves the window buffer implementation from vector to deque

## Type of change

- [ ] Documentation (non-breaking change that adds or improves the documentation)
- [x] New feature or enhancement (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking change that improves code/performance)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Testing checklist

- [ ] Unit tests pass (e.g. `dbt-build --unittest`)
- [x] Minimal system quicktest passes (`pytest -s minimal_system_quick_test.py`)
- [x] Full set of integration tests pass (`daqsystemtest_integtest_bundle.sh`)
- [ ] Python tests pass if applicable (e.g. `python -m pytest`)
- [ ] Pre-commit hooks run successfully if applicable (e.g. `pre-commit run --all-files`)

## Further checks

- [x] Code is commented where needed, particularly in hard-to-understand areas
- [ ] Code style is correct (`dbt-build --lint`, and/or see https://dune-daq-sw.readthedocs.io/en/latest/packages/styleguide/)
- [ ] If applicable, new tests have been added or an issue has been opened to tackle that in the future.
  (Indicate issue here: # (issue))

### CODE REVIEW

File: src/TAMakerADCSimpleWindowAlgorithm.cpp [hunk 1]
```diff
@@ -84,25 +152,55 @@ TAMakerADCSimpleWindowAlgorithm::construct_ta() const
...
+  for( const auto& tp : m_current_window.tp_list ) {
+    
+    ch_min = std::min(ch_min, tp.channel);
+    ch_max = std::max(ch_max, tp.channel);
+    time_min = std::min(time_min, tp.time_start);
+    time_max = std::max(time_max, tp.time_start + tp.samples_over_threshold * 32);
+    if (tp.adc_peak > adc_peak) {
+      adc_peak = tp.adc_peak;
+      ch_peak = tp.channel;
+      time_peak = time_peak;
```
Comment (MRiganSUSX) [inline src/TAMakerADCSimpleWindowAlgorithm.cpp]: Seems like `time_peak` was never calculated/set properly ?
Should this be:
```
time_peak = tp.time_start + tp.samples_to_peak * 32;
```
?

File: src/TAMakerADCSimpleWindowAlgorithm.cpp [hunk 2]
```diff
@@ -84,25 +152,55 @@ TAMakerADCSimpleWindowAlgorithm::construct_ta() const
...
+
+  // Copy the queue into the vector
+  // And compute TA parameters
+  for( const auto& tp : m_current_window.tp_list ) {
+    
+    ch_min = std::min(ch_min, tp.channel);
+    ch_max = std::max(ch_max, tp.channel);
+    time_min = std::min(time_min, tp.time_start);
+    time_max = std::max(time_max, tp.time_start + tp.samples_over_threshold * 32);
+    if (tp.adc_peak > adc_peak) {
```
Comment (MRiganSUSX) [inline src/TAMakerADCSimpleWindowAlgorithm.cpp:179]: There is a little problem with this comparison, especially given the initial setup of vars a few lines above:
```
  uint64_t adc_peak{latest_tp_in_window.adc_peak};
  uint64_t ch_peak{dunedaq::trgdataformats::INVALID_CHANNEL};
  timestamp_t time_peak{dunedaq::trgdataformats::INVALID_TIMESTAMP};
```
If the latest tp is actually the one with the highest ADC peak, then this comparison (`tp.adc_peak > adc_peak`) will never be true and we will never properly set the `ch_peak`, `time_peak`. 

Much better to either:
- set the initial adc value to 0
```
uint64_t adc_peak = 0;
```
- or even better set the initial vars relative to first tp, so that we have real physical values:
```
  const TriggerPrimitive& first_tp = m_current_window.tp_list.front();
  
  uint64_t adc_peak{first_tp.adc_peak};
  uint64_t ch_peak{first_tp.channel};
  timestamp_t time_peak{first_tp.time_start + first_tp.samples_to_peak * 32};
```
the `time_peak` has another problem, which is described above.

File: src/TAMakerADCSimpleWindowAlgorithm.cpp [hunk 3]
```diff
@@ -14,12 +14,80 @@
...
+  // Erase the TPs from the window.
+  tp_list.erase(tp_list.begin(), tp_list.begin()+n_tps_to_erase);
+  // Make the window start time the start time of what is now the
+  // first TP.
+  if(tp_list.size()!=0){
+    time_start = tp_list.front().time_start;
+    add(input_tp);
+  }
+  else reset(input_tp);
+};
```
Comment (MRiganSUSX) [inline src/TAMakerADCSimpleWindowAlgorithm.cpp]: Since you nicely changed this from `vector` to `deque`, we should take full advantage of its features. We can simplify this logic by using `pop_front()` and combining the math/erasure steps into a single loop:
```
void 
TAMakerADCSimpleWindowAlgorithm::Window::move(TriggerPrimitive const &input_tp, timestamp_t const &window_length){
  // Remove TPs from the front of the queue that fall outside the new window.
  while (!tp_list.empty() && (input_tp.time_start - tp_list.front().time_start >= window_length)) {
    adc_integral -= tp_list.front().adc_integral;
    tp_list.pop_front();
  }

  // Update the window start time and add the new TP.
  if (!tp_list.empty()) {
    time_start = tp_list.front().time_start;
    add(input_tp);
  } else {
    reset(input_tp);
  }
}
```

File: src/TAMakerADCSimpleWindowAlgorithm.cpp [hunk 4]
```diff
@@ -84,25 +152,55 @@ TAMakerADCSimpleWindowAlgorithm::construct_ta() const
...
+      time_peak = time_peak;
+    }
+
+    tp_list.push_back(tp);
+  }
+
   TriggerActivity ta;
-  ta.time_start = m_current_window.time_start;
-  ta.time_end = latest_tp_in_window.time_start + latest_tp_in_window.samples_over_threshold * 32;  // FIXME: Replace the hard-coded SOT to TOT scaling.
-  ta.time_peak = latest_tp_in_window.samples_to_peak * 32 + latest_tp_in_window.time_start;  // FIXME: Replace STP to `time_peak` conversion.
```
Comment (MRiganSUSX) [inline src/TAMakerADCSimpleWindowAlgorithm.cpp:93]: Since we are removing the `FIXME` comments: were they fixed?

File: src/TAMakerADCSimpleWindowAlgorithm.cpp [hunk 5]
```diff
@@ -14,12 +14,80 @@
...
 using Logging::TLVL_DEBUG_LOW;
 using Logging::TLVL_IMPORTANT;
 
+void
+TAMakerADCSimpleWindowAlgorithm::Window::add(TriggerPrimitive const &input_tp){
+  // Add the input TP's contribution to the total ADC and add it to
+  // the TP list.
+  adc_integral += input_tp.adc_integral;
+  tp_list.push_back(input_tp);
+};
```
Comment (MRiganSUSX) [inline src/TAMakerADCSimpleWindowAlgorithm.cpp]: This trailing `;` is not needed in the .cpp (I assume just a leftover from the copy from the header). Same for `move` and `reset`.

**Review by MRiganSUSX — CHANGES_REQUESTED** [review]
Hi @alessandrothea,
If you don't mind, I have few suggestions. Some are logical (with actual effect), others are just nice-to-haves.

File: src/TAMakerADCSimpleWindowAlgorithm.cpp (hunk 1 above)
Comment (alessandrothea) [reply src/TAMakerADCSimpleWindowAlgorithm.cpp]: Yes!

File: src/TAMakerADCSimpleWindowAlgorithm.cpp (hunk 2 above)
Comment (alessandrothea) [reply src/TAMakerADCSimpleWindowAlgorithm.cpp:179]: Fixed!

File: src/TAMakerADCSimpleWindowAlgorithm.cpp (hunk 4 above)
Comment (alessandrothea) [reply src/TAMakerADCSimpleWindowAlgorithm.cpp:93]: Sorry, what FIXME?

File: src/TAMakerADCSimpleWindowAlgorithm.cpp (hunk 5 above)
Comment (alessandrothea) [reply src/TAMakerADCSimpleWindowAlgorithm.cpp]: Done.

File: src/TAMakerADCSimpleWindowAlgorithm.cpp (hunk 4 above)
Comment (MRiganSUSX) [reply src/TAMakerADCSimpleWindowAlgorithm.cpp:93]: Comments in the last two lines.

File: src/TAMakerADCSimpleWindowAlgorithm.cpp (hunk 3 above)
Comment (alessandrothea) [reply src/TAMakerADCSimpleWindowAlgorithm.cpp]: Maybe, but I still find the "find new boundaries+bulk erase" approach preferable compared to a "pop loop".
`dequeue::erase` is likely to be optimised, compared to a recursive pop.
I'd like to keep the current implementation for now.

File: src/TAMakerADCSimpleWindowAlgorithm.cpp (hunk 4 above)
Comment (alessandrothea) [reply src/TAMakerADCSimpleWindowAlgorithm.cpp:93]: Found them and fixed.

**Comment by alessandrothea** [comment]
[event_displays_43130.0000.orig.pdf](https://github.com/user-attachments/files/25791437/event_displays_43130.0000.orig.pdf)
[event_displays_43130.0000.new.pdf](https://github.com/user-attachments/files/25791439/event_displays_43130.0000.new.pdf)
TAs generated with `trgtools` emulator before and after the patch

**Review by MRiganSUSX — APPROVED** [review]
Thanks for the updates @alessandrothea . Looks good now.

I've run the integtest bundle and all but 1 test passed. The error in the one (`example_system_test`) was not caused by these changes 
```
🚨 Problem(s) found in logfile /log/log_mrigan_ehn1-local-2x3-config-mrigan-hYtc_df-03_2026-03-06-16-14-06.txt:
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
```

I have NOT done testing with either replay nor at ehn1, so that is my last recommendation. Comparisons using the same dataset before/after (as you did) is also very nice.
